before_install:
  - sudo apt-get install -y unzip
  - wget https://releases.hashicorp.com/packer/0.12.2/packer_0.12.2_linux_amd64.zip -O ~/packer.zip
  - unzip ~/packer.zip
  - sudo mv ~/packer /usr/local/bin/

install:
  - packer --version
