language: python
addons:
  apt:
    sources:
      - sourceline: deb http://download.virtualbox.org/virtualbox/debian precise contrib
        key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc 
        key-url: https://www.virtualbox.org/download/oracle_vbox.asc 
before_install:
  - sudo apt-get update
  - sudo apt-get install -y linux-headers-3.13.0-103-generic
  - sudo apt-get install -y linux-headers-generic
  - sudo apt-get install -y --force-yes git unzip virtualbox-5.1 dkms 
  - wget https://releases.hashicorp.com/packer/0.12.2/packer_0.12.2_linux_amd64.zip -O ~/packer.zip
  - unzip ~/packer.zip -d ~/
  - sudo mv ~/packer /usr/local/bin/
  - git clone https://github.com/defionscode/centos7_builder.git ~/builder

install: 
  - travis_wait 30 cd ~/builder; packer build template.json
  - cd ~/builder; ls -arlth
